config/routes.rb
SocialApp::Application.routes.draw do
  resources :users do
    resources :friend_circles
    get "password_reset"
  end

  resource :session do
    post "send_reset_email"
  end
end

app/models/friend_circle.rb
class FriendCircle < ActiveRecord::Base
  attr_accessible :owner_id, :name

  validates :owner_id, :name, presence: true

  belongs_to(:owner,
  class_name: "User",
  primary_key: :id,
  foreign_key: :owner_id
  )

  has_many(:friend_circle_memberships,
  class_name: "FriendCircleMembership",
  primary_key: :id,
  foreign_key: :friend_circle_id
  )

end

app/models/friend_circle_membership.rb
class FriendCircleMembership < ActiveRecord::Base
  attr_accessible :friend_circle_id, :friend_id

  validates :friend_id, :friend_circle_id, presence: true

  belongs_to(:friend_circle,
  class_name: "FriendCircle",
  primary_key: :id,
  foreign_key: :friend_circle_id
  )

  has_many(:members,
  class_name: "User",
  primary_key: :id,
  foreign_key: :friend_id
  )

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_digest, :session_token, :password

  before_validation :session_token, :must_be_set
  validates :email, uniqueness: true
  validates :email, :password_digest, :session_token, presence: true

  has_many(:friend_circles,
  class_name: "FriendCircle",
  primary_key: :id,
  foreign_key: :owner_id
  )

  has_many(:memberships,
  class_name: "FriendCircleMembership",
  primary_key: :id,
  foreign_key: :friend_id
  )

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
     BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private

  def must_be_set
    reset_session_token! if self.session_token.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
  include SessionsHelper
end

app/controllers/friend_circles_controller.rb
class FriendCirclesController < ApplicationController
  def new
    render :new
  end


  def create
    @friend_circle = FriendCircle.new(:name => params[:friend_circle][:name])

    @friend_circle.friend_circle_memberships.new(params[:friend_circle_memberships][:members])
    fail


  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_email(params[:user][:email])

    if @user.nil?
      render :new
    elsif @user.is_password?(params[:user][:password])
      log_in!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:token] = nil
    redirect_to new_session_url
  end

  def send_reset_email
    @user = User.find_by_email(params[:user][:email])
    msg = UserMailer.forgot_password(@user)
    msg.deliver!
    render :new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    render :index
  end

  def new
    render :new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      log_in!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def password_reset
    @user = User.find_by_session_token(params[:session_token])
    log_in!(@user)
    render :password_reset
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes!(params[:user])
    redirect_to user_url(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_circles_helper.rb
module FriendCirclesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:token])
  end

  def log_in!(user)
    user.reset_session_token!
    session[:token] = user.session_token
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friend_circles/new.html.erb
<form action="<%= user_friend_circles_url %>" method="POST" accept-charset="utf-8">
	<label for="friend_circle_name">Friend Circle Name: </label>
	<input type="text" name="friend_circle[name]" id="friend_circle_name">
	<br>
  <input type="hidden" name="friend_circle_memberships[][members]" value="">

	<br>
	<% User.all.each do |user| %>
	<% next if user.id == current_user.id %>

		<input type="checkbox" name="friend_circle_memberships[][members]" id="member" value="<%= user.id %>">
	  <label for="member"><%= user.email %></label>
	  <br>

	<% end %>

	<p><input type="submit" value="Create Friend Circle"></p>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if logged_in? %>
		<%= current_user.email %>
		<%= button_to "Log Out", session_url, method: :delete %>
	<% else %>

		<%= link_to "Log In", new_session_url, method: :get %>
		<%= link_to "Sign Up", new_user_url, method: :get %>
	<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="POST" accept-charset="utf-8">
	<label for="user_email">Email</label>
	<input type="text" name="user[email]" value="" id="user_email"><br>

	<label for="user_password">Password</label><input type="text"
				name="user[password]" value="" id="user_password"><br>

	<p><input type="submit" value="Create Account"></p>
</form>

app/views/users/password_reset.html.erb
<h1>Password reset</h1>

<form action="<%= user_url(@user) %>" method="POST" accept-charset="utf-8">
	<input type="hidden" name="_method" value="PUT">

	<label for="user_password">Password</label><input type="text"
				name="user[password]" value="" id="user_password"><br>

	<p><input type="submit" value="Create Account"></p>
</form>

app/views/users/show.html.erb
<%= @user.email %>